### ISSUE TITLE
Change default date range and date format

### ISSUE THREAD

**Issue by BradNut** [davquar/halfdot#28]
Request to add default date range picker like on your instance settings.

Also, request to add the option to change the date format from YYYY/mm/dd to other formats.

**Comment by davquar** [comment]
> Request to add default date range picker like on your instance settings.

Do you mean having presets like "yesterday", "this week", etc? If yes, great suggestion.

---

In any case, thank you for the suggestions, they are good and improve the user experience. I'll work on them soon; I cannot guarantee time because in this period I have quite a lot to do.

**Comment by BradNut** [comment]
For the date range picker yes options like yesterday or last 24 hours.

Like the settings on an instance: ![Screenshot_20230212-093616_1](https://user-images.githubusercontent.com/6621295/218327249-26fcdf3d-b2c9-418a-b036-f7385f5bff78.png)

For the date format I am referring to how the app displays dates: 
![Screenshot_20230212-093835_1](https://user-images.githubusercontent.com/6621295/218327328-649dcf64-b3c5-4827-b751-f64a7ca9c0c2.png)

It is in the format of YYYY-mm-dd but it would be nice to be able to change this to mm-dd-YYYY or mm/dd/YYYY and other options people may want for formatting on the UI.

For example from another app I use: 
![Screenshot_20230212-094040_1](https://user-images.githubusercontent.com/6621295/218327446-165a0c43-d12b-46ad-994c-8251a85ceb3e.png)

**Comment by davquar** [comment]
All clear, thanks for clarifying 👍🏼

**Comment by davquar** [comment]
@BradNut for some reason the F-Droid pipeline didn't catch the new release here on GitHub; I am going to investigate on the weekend

**Comment by BradNut** [comment]
@davquar Sounds good. Thank you!

**Comment by davquar** [comment]
A little update: F-Droid caught the update and correctly updated the metadata file.

- Build log: https://monitor.f-droid.org/builds/log/it.davquar.halfdot/23
- Metadata update commit: https://gitlab.com/fdroid/fdroiddata/-/commit/ed4cd102d934b6cbb20499c452380391f170eca2

But for some reason the update is not in the catalog.

---

Update 2: apparently it is an F-Droid issue that has impacted multiple apps:

- https://gitlab.com/fdroid/fdroiddata/-/issues/2952
- https://gitlab.com/fdroid/admin/-/issues/382
- https://gitlab.com/fdroid/fdroidclient/-/issues/2566

We should wait :)

**Comment by davquar** [comment]
@BradNut It's published now 🥳

**Comment by BradNut** [comment]
Got the update. Thank you!
