### ISSUE TITLE
Compatibility with managed Umami Cloud

### ISSUE THREAD

**Issue by SimplyVoid** [davquar/halfdot#35]
if i put `https://https://analytics.umami.is/`
in the instance url the app freezes, removing the `/` makes it work again.

also for some reasons I've putted correct credentials yet there is a credential error. I have logout from `https://analytics.umami.is` and tried to login with same credentials and it worked just fine

**Comment by davquar** [comment]
> if i put `https://https://analytics.umami.is/`
> in the instance url the app freezes, removing the `/` makes it work again.
> 
> also for some reasons I've putted correct credentials yet there is a credential error. I have logout from `https://analytics.umami.is` and tried to login with same credentials and it worked just fine

Hello @SimplyVoid 

Thank you for the report. Which Umami and HalfDot versions?

Also, can you confirm that `https://https://analytics.umami.is` is a paste error and instead you tried with `https://analytics.umami.is`?

**Comment by SimplyVoid** [comment]
> Hello @SimplyVoid
> 
> Thank you for the report. Which Umami and HalfDot versions?
> 
> Also, can you confirm that `https://https://analytics.umami.is` is a paste error and instead you tried with `https://analytics.umami.is`?

aah sry it was a paste error as the url box had `https://` prewritten, none the less I'm using latest version (Version 2.0.0) from fdroid.
### also here're some previews:

This one is with tailing `/`, it's been frozen like this whole time
![Screenshot_20230521-192654~2](https://github.com/davquar/halfdot/assets/75927811/f0a24944-565e-48d1-ac67-470579ad2f0f)
---
and this one is without tailing `/` but as you can see credentials error
![Screenshot_20230521-192645](https://github.com/davquar/halfdot/assets/75927811/247fb6a4-9b7a-4455-bca8-95e1f5e578c1)

**Comment by davquar** [comment]
Hm, which remote Umami version?

Also, is this the first time you are using HalfDot, or has the app started to behave like that now?

**Comment by SimplyVoid** [comment]
> Hm, which remote Umami version?
> 
> Also, is this the first time you are using HalfDot, or has the app started to behave like that now?

probably the latest umami remote version as it's provided by the developers of umami & I'm using halfdot (& umami) for the first time

**Comment by davquar** [comment]
Ok so the trailing slash problem can be related to a misconfiguration in the app's HTTPS client or in the remote Umami's webserver (or both :D).

Regarding the credentials, maybe the managed Umami instance has a slightly different API.

For both issues, in any case I need to check and try to reproduce them.

**Comment by SimplyVoid** [comment]
> Ok so the trailing slash problem can be related to a misconfiguration in the app's HTTPS client or in the remote Umami's webserver (or both :D).
> 
> Regarding the credentials, maybe the managed Umami instance has a slightly different API.
> 
> For both issues, in any case I need to check and try to reproduce them.

as far as the 2nd issue with credentials i think the main reason of it not working is if you try to login through `https://analytics.umami.is` it redirects to `https://cloud.umami.is` for login but again all data is available on `https://analytics.umami.is/dashboard`
using `https://cloud.umami.is` doesn't work as the app doesn't recognize this as a analytics server.. I don't know how hosted server works so wasn't sure if it's the issue

**Comment by davquar** [comment]
Hello @SimplyVoid,
It should be fixed in release https://github.com/davquar/halfdot/releases/tag/v2.0.1.

Thank you for the report 👍🏼

**Comment by SimplyVoid** [comment]
> Hello @SimplyVoid, It should be fixed in release https://github.com/davquar/halfdot/releases/tag/v2.0.1.
> 
> Thank you for the report 👍🏼

thank you for the quick response & bug fix❤️ but one more thing, can you add apk to the Releases tab? I'd love to use [obtainium](https://github.com/ImranR98/Obtainium) to update the app directly through github

**Comment by davquar** [comment]
It is an idea, I'll definitely add to the list of thing to do :)

**Comment by davquar** [comment]
Thank you for reporting that: I really appreciate it. Unfortunately I'll not be able to work on it for at least one week. In the meantime I updated this issue considering the new discoveries.
