### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by depgod** [davquar/halfdot#40]
Does the app accept the username or the email id? I tried both but failed to login.

**Comment by davquar** [comment]
Hello, the app accepts the username. Are you using a self-hosted instance or the managed one?
Also, mind that the latest version of the app may not work with Umami < 2.6.2.

**Comment by depgod** [comment]
Hi, I am using the managed one.

**Comment by kokamkarsahil** [comment]
> Hi, I am using the managed one.
Are you facing the same error as the managed one?

![Image.png](https://github.com/davquar/halfdot/assets/84327775/ab3b660f-9dce-43e6-b1a5-2960e94c138e)

**Comment by depgod** [comment]
Hi, I am using the managed one.

**Comment by davquar** [comment]
It looks like the login is OK, but there are issues getting websites data.

The may have changed something again in their API for the managed server; or maybe it is just temporary.
I have to check and reproduce the issue.

**Comment by kokamkarsahil** [comment]
> It looks like the login is OK, but there are issues getting websites data with the token retrieved after the login.
> 
> The may have changed something again in their API for the managed server; or maybe it is just temporary.
> I have to check and reproduce the issue.

It's looks like the dashboard has moved to `analytics.eu.umami.is` from `analytics.umami.is`. Which might be causing the issue in my case.

**Comment by depgod** [comment]
Probably in my case too

**Comment by davquar** [comment]
Yes, I confirm that there is a new `region` entry in the JSON that you get after login, that evidently determines the domain to use to get data.

The good news is that there is no reason to support that behavior, because now I can see that `cloud.umami.is`· is proxying requests for `analytics.<region>.umami.is`.
