### ISSUE TITLE
NoSuchMathodError on Summary Rendering

### ISSUE THREAD

**Issue by BradNut** [davquar/halfdot#43]
The summary rendering is throwing the error:
```
Error: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("value")
```

Image of the error:
![Screenshot_20240506-083726](https://github.com/davquar/halfdot/assets/6621295/9421448e-3e57-4871-bae5-8921bacbdb76)

Happened for any date range with or without data in the range.

**Comment by davquar** [comment]
Hey,

Thank you for reporting!

I'll have some time at the end of the week to fix it.
